# Generated by Django 6.0.4 on 2026-05-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('timeout', models.PositiveIntegerField(help_text='Timeout in seconds')),
                ('alert_email', models.EmailField(help_text='Email to send alerts to', max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('paused', 'Paused')], default='active', max_length=10)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_checked', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
